### ISSUE TITLE
Admin UI/Netgen layouts tabs not working

### ISSUE THREAD

**Issue by yadimen** [netgen/media-site#1]
We did install as per install instructions, front end looks awesome and good.. however, the admin and netgen layouts tab don't seems to be working.. While inspecting, there were number of Jquery not defined errors. Are we missing any key steps or procedures here, please advice.

**Comment by emodric** [comment]
Hi, did you use the the apache/nginx vhosts provided by this repo, which would allow using legacy frontend assets?

Specifically, for Apache: https://github.com/netgen/media-site/blob/master/doc/apache2/netgen-site-vhost.conf#L100-L105, or for Nginx: https://github.com/netgen/media-site/blob/master/doc/nginx/ez_params.d/ez_legacy_rewrite_params

**Comment by emodric** [comment]
Solved with https://github.com/netgen/media-site/commit/af6f4ef8c8a6bc0b4714a27f7af64d632044146c and `1.0.2` tag.
