### ISSUE TITLE
Error when creating a new project

### ISSUE THREAD

**Issue by milospetkovic** [netgen/media-site#107]
I've followed installation instructions, and there's an error during installation with command:
`composer create-project netgen/media-site`

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1

In StorageEngineFactory.php line 71:
Invalid storage engine 'legacy'. Could not find any service tagged with ezpublish.storageEngine with alias legacy. 

Any hint how to solve this?

OS: Ubuntu 20.04, PHP 7.4.33,  Apache/2.4.41, MariaDB 10.3.37

**Comment by milospetkovic** [comment]
Thanks.
I've deleted `media-site`, then `composer create-project netgen/media-site`, the same error appears,
and in composer.json I've added
"symfony/dependency-injection": "5.4.17"
to the "conflict" property (firstly, I've added as "5.4.*", but it must be the exact version).
composer update -> and voila :) I'll close the issue.

**Comment by emodric** [comment]
I'm glad it worked for you! :)
