### ISSUE TITLE
sql-errors

### ISSUE THREAD

**Issue by oyvindlh** [netgen/media-site#13]
Hi =)
When installing media-site from scratch and (for instance with demodata) I get:

Search engine re-indexing, executing command ezplatform:reindex
Re-indexing started for search engine: eZ Platform Legacy (SQL) Search Engine

Purging index...
Re-Creating index for 201 items across 5 iteration(s), using single (current) process:
 0/5 [>---------------------------]   0%
In AbstractMySQLDriver.php line 60:

  An exception occurred while executing 'SELECT `usr`.`contentobject_id`, `us
  r`.`login`, `usr`.`email`, `usr`.`password_hash`, `usr`.`password_hash_type
  `, `usr`.`password_updated_at` FROM `ezuser` usr WHERE `usr`.`contentobject
  _id` = ?' with params [10]:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usr.password_update
  d_at' in 'field list'

In PDOStatement.php line 119:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usr.password_update
  d_at' in 'field list'

In PDOStatement.php line 117:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usr.password_update
  d_at' in 'field list'

**Comment by emodric** [comment]
Hey Øyvind!

Are you using the correct version of `netgen/media-site-data` ? Because it contains the SQL data required for `password_updated_at` feature: https://github.com/netgen/media-site-data/commit/f26248080a7e3290be87a4d1eab188866310ba96

**Comment by emodric** [comment]
I think this can be safely closed as obsolete.
