### ISSUE TITLE
CSS overlay ellipsis not displaying

### ISSUE THREAD

**Issue by wizhippo** [netgen/media-site#17]
https://github.com/netgen/media-site/blob/1159898eb77309b7bd9a9bf36e23630ff7559568/src/AppBundle/Resources/sass/content/item_view_types/_overlay.scss#L50

in Chrome this stops `text-overflow: ellipsis;` from working.

**Comment by emodric** [comment]
Not sure what happened here :)

**Comment by wizhippo** [comment]
It was all me.  Another custom style conflicted. Specifically I had a no-wrap in a parent.
