### ISSUE TITLE
Adminui fails with missing "folder"

### ISSUE THREAD

**Issue by HolzwegDev** [netgen/media-site#205]
fix:

INSERT INTO `ezcontentclass` (`id`, `version`, `always_available`, `contentobject_name`, `created`, `creator_id`, `identifier`, `initial_language_id`, `is_container`, `language_mask`, `modified`, `modifier_id`, `remote_id`, `serialized_description_list`, `serialized_name_list`, `sort_field`, `sort_order`, `url_alias_name`)
VALUES
	(1, 0, 1, '<short_name|name>', 1024392098, 14, 'folder', 2, 1, 2, 1448831672, 14, 'a3d405b81be900468eb153d774f4f0d2', 'a:0:{}', 'a:1:{s:6:\"eng-GB\";s:6:\"Folder\";}', 1, 1, NULL);

**Comment by emodric** [comment]
Hi!

This is already reported to Ibexa in https://issues.ibexa.co/issue/IBX-8285 and overriden here with https://github.com/netgen/media-site/commit/994ae1769368fc9efce13f1abe3532cf20382db2, so there is no real reason to use this SQL insert.

Thanks for the report though!
